
export const DATATABLE_ADD = 'DATATABLE/ADD';
export const DATATABLE_UPDATE = 'DATATABLE/UPDATE';
export const DATATABLE_DELETE = 'DATATABLE/DELETE';
export const DATATABLE_SORT = 'DATATABLE/SORT';
export const DATATABLE_FETCH = 'DATATABLE/FETCH';
export const DATATABLE_FETCH_STARTED = 'DATATABLE/FETCH/STARTED';
export const DATATABLE_FETCH_SUCCESS = 'DATATABLE/FETCH/SUCCESS';
export const DATATABLE_FETCH_ERROR = 'DATATABLE/FETCH/ERROR';
export const DATATABLE_FETCH_LOADING = 'DATATABLE/LOADING/LOADING';