export const DATATABLE_LOAD = 'DATATABLE/LOAD';
export const DATATABLE_ADD = 'DATATABLE/ADD';
export const DATATABLE_UPDATE = 'DATATABLE/UPDATE';
export const DATATABLE_DELETE = 'DATATABLE/DELETE';
export const DATATABLE_SORT = 'DATATABLE/SORT';